apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv02
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs
    path: gitlab-pv02
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
