apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv05
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs
    path: gitlab-pv05
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
