apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv03
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs
    path: gitlab-pv03
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
