apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv04
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs
    path: gitlab-pv04
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
